### ISSUE TITLE
Setting datadog.logLevel to DEBUG removes the DD_LOG_LEVEL env variable

### ISSUE THREAD

**Issue by jebbench** [DataDog/helm-charts#168] opened 2021-02-19 10:19 UTC
**Describe what happened:**
Setting `datadog.logLevel` to DEBUG removed the `DD_LOG_LEVEL` env variable

**Describe what you expected:**
For DD_LOG_LEVEL to be set to DEBUG

**Steps to reproduce the issue:**
Using chart version 2.8.5 and the values:

```
datadog:
  apiKeyExistingSecret: ${kubernetes_secret.datadog_secret.metadata.0.name}
  appKeyExistingSecret: ${kubernetes_secret.datadog_secret.metadata.0.name}
  site: datadoghq.eu
  logLevel: DEBUG
  env:
    - name: DD_CONTAINER_EXCLUDE
      value: |-
        kube_namespace:kube-system
        kube_namespace:datadog
  kubeStateMetricsEnabled: true
  clusterChecks:
    enabled: true
  collectEvents: true
  logs:
    enabled: true
    containerCollectAll: true
  apm:
    enabled: true
  processAgent:
    enabled: true
    processCollection: true
  orchestratorExplorer:
    enabled: true
    container_scrubbing:
      enabled: false
  dogstatsd:
    port: 8125
    useHostPort: true
    nonLocalTraffic: true
clusterAgent:
  enabled: true
  token: ${random_password.datadog_cluster_agent_token.result}
```

Produces a deamon set without any reference to DD_LOG_LEVEL.

**Additional environment details (Operating System, Cloud provider, etc):**
Deploying to GKE using Terraform.

**Comment by jebbench** [comment] 2021-02-19 10:28
Setting the log level to WARN and then back to DEBUG seems to have fixed it.

**Comment by vboulineau** [comment] 2021-02-22 10:33
Hello @jebbench,

I've checked the templates code and it looks correct, `logLevel` is always set as default `values.yaml` has `logLevel: INFO`.
I tested with Helm3 and I was not able to reproduce the issue, are you able to reproduce it using `helm template` somehow?

Best,
Vincent.

**Comment by ahmed-mez** [comment] 2021-02-24 08:48
Hi @jebbench 

Same as Vincent, I couldn't reproduce either. But it seems like you managed to fix it on your side so I'm closing this issue.
Please let us know if you have any other questions!

Thanks.

**Closed by ahmed-mez** 2021-02-24 08:48 UTC

**Comment by jebbench** [comment] 2021-02-25 09:25
I think I updated the chart version at the same time so it might have been related to that - changing the log level and changing it back cleared it up for me anyway.
