### ISSUE TITLE
setting networkMonitoring.enabled to false results in errors

### ISSUE THREAD

**Issue by pdeva** [DataDog/helm-charts#1023] opened 2023-04-30 07:54 UTC
**Describe what happened:**
setting `datadog.networkMonitoring.enabled` to `false` results in system-probe container being spun up, exiting and causing the pod to be in error state.

**Describe what you expected:**
setting `datadog.networkMonitoring.enabled` to `false`  should be equivalent behavior to omitting setting `datadog.networkMonitoring.enabled` at all, since it defaults to `false`.  however, setting the value to `false` causes change in behavior, which is the pod crashing. 

**Steps to reproduce the issue:**

set `datadog.networkMonitoring.enabled` to `false` in your helm chart config

**Additional environment details (Operating System, Cloud provider, etc):**

EKS Bottlerocket arm64
chart 3.27.0

**Comment by levan-m** [comment] 2023-08-25 19:15
Hello,
Thanks for submitting the issue. I'm not able to reproduce the problem you are facing. 

I rendered and compared templates from below three commands
```sh
helm template datadog datadog/datadog --version 3.27.0 \
  --set datadog.apiKey=API_KEY \
  --set datadog.appKey=APP_KEY 

helm template datadog datadog/datadog --version 3.27.0 \
  --set datadog.apiKey=API_KEY \
  --set datadog.appKey=APP_KEY \
  --set datadog.networkMonitoring.enabled=false

helm template datadog datadog/datadog --version 3.27.0 \
  --set datadog.apiKey=API_KEY \
  --set datadog.appKey=APP_KEY \
  --set datadog.networkMonitoring.enabled=true
```
First and second produced identical manifests (besides some checksums), last one add `system-probe` container and other settings.

Using same setting to setup agent on EKS Fargate (ARM but not Bottlerocket, but I doubt that could be an issue since helm rendering is identical when omitting the setting or when setting the default value) cluster produced same result. With first two didn't no `system-probe` was created, with the last one it did and didn't cause any errors.

Could you please confirm you are setting only `datadog.networkMonitoring.enabled` and provide steps to reproduce the issue?

**Comment by levan-m** [comment] 2023-10-11 14:52
Resolving since we haven't received any update for over a month. Feel free to reopen if the problem arises.

**Closed by levan-m** 2023-10-11 14:52 UTC
Labels: chart/datadog, waiting-user-feedback
