### ISSUE TITLE
Agent intake timeouts on GKE Autopilot

### ISSUE THREAD

**Issue by ags** [DataDog/helm-charts#467] opened 2021-12-12 23:27 UTC
**Describe what happened:**

We installed the datadog/datadog chart using the following values:

```yaml
providers:
  gke:
    autopilot: true

clusterAgent:
  enabled: true
  metricsProvider:
    enabled: true
  admissionController:
    enabled: true
    mutateUnlabelled: false

datadog:
  apiKey: ...
  appKey: ...
  logs:
    enabled: true
  apm:
    socketEnabled: false
    portEnabled: true
    port: 8126
  dogstatsd:
    port: 8125
    useHostPort: true
    nonLocalTraffic: true
    useSocketVolume: false
  kubeStateMetricsEnabled: false
  kubeStateMetricsCore:
    enabled: true
```

Container logs are being collected, and the cluster agent admission controller does appear to be correctly setting the `DD_AGENT_HOST` env var to host node IPs like `10.128.0.48`, but containers are unable to send traces or metrics to the agent. The datadog-go library produces warnings like:

```
WARN: DIAGNOSTICS Unable to reach agent intake: Post "http://10.128.0.48:8126/v0.4/traces": dial tcp 10.128.0.48:8126: i/o timeout (Client.Timeout exceeded while awaiting headers)
```

There are no VPC firewall rules other than the defaults created by GKE Autopilot. Even adding rules to allow ingress and egress from `0.0.0.0/0` doesn't seem to allow containers to talk to the agent.

The [GKE Autopilot docs](https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-overview#host_options_restrictions) say that `hostPort` is not supported, but using values based on https://docs.datadoghq.com/integrations/gke/?tab=autopilot, e.g.

```yaml
providers:
  gke:
    autopilot: true

clusterAgent:
  enabled: true
  metricsProvider:
    enabled: true
  admissionController:
    enabled: true
    mutateUnlabelled: false

datadog:
  apiKey: ...
  appKey: ...
  logs:
    enabled: true
  apm:
    enabled: true
```

produced the following warnings:

```
WARNING: dogstatsd with Unix socket is not supported on GKE Autopilot
WARNING: APM with Unix socket is not supported on GKE Autopilot
````

and didn't work (which was expected). Is there a way to run the agent on GKE Autopilot nodes that allows containers to submit APM traces / statsd metrics? It seems like we're missing something as APM is mentioned explicitly in the [Datadog GKE autopilot docs](https://docs.datadoghq.com/integrations/gke/?tab=autopilot), and we're a bit confused about what we're doing wrong!

**Describe what you expected:**

Containers running on GKE Autopilot would be able to send APM traces and statsd metrics to the agent running on the host by configuring clients using the `DD_AGENT_HOST` env var provided by the admission controller.

**Steps to reproduce the issue:**

1. Create a new private GKE Autopilot cluster
2. `helm install datadog-agent -f values.yml datadog/datadog`, where `values.yml` is the config above
3. Deploy a container that has the admission label and tries to use tracing / statsd:

```yaml
spec:
  template:
    metadata:
      labels:
        admission.datadoghq.com/enabled: "true"
```

```go
statsd, err := statsd.New(os.Getenv("DD_AGENT_HOST"))
if err != nil {
  log.Fatal(err)
}
defer statsd.Close()

tracer.Start(
  tracer.WithEnv("test"),
  tracer.WithService("demo"),
  tracer.WithDebugMode(true),
)
defer tracer.Stop()
```

4. Get warnings about timing out connecting to the agent, and no traces or metrics reported at runtime

**Additional environment details (Operating System, Cloud provider, etc):**

Helm chart version: datadog-2.27.2

**Comment by dlouvier** [comment] 2021-12-15 17:17
Hi @ags 

I can also confirm the issue. This is not happening in our still not upgraded Autopilot GKE cluster in v.1.19

I tried to remediate it setting up a service in front of the datadog agents pods and replacing the `DD_AGENT_HOST` value from `status.hostIP` to `datadog-agent-issue.default` and it seems to work.

```
Name:              datadog-agent-issue
Namespace:         default
Labels:            app=datadog-agent-issue
Annotations:       cloud.google.com/neg: {"ingress":true}
Selector:          app.kubernetes.io/component=agent
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                10.x.x.x
IPs:               10.x.x.x
Port:              8126-8126  8126/TCP
TargetPort:        8126/TCP
Endpoints:         10.x.0.x:8126,10.x.0.x:8126,10.x.0.x:8126 + 6 more...
Session Affinity:  None
Events:            <none>
```

**Comment by CharlyF** [comment] 2021-12-28 00:54
Hi all - I can indeed reproduce using the host ip in a 1.21 cluster. I can reach the pods using their ips directly (not that it's helpful, but is worth noting).
@ags could you share the version of Kubernetes the cluster is running?

I am going to reach out to our Autopilot contacts to see if something has changed on their end.
I apologize for the headache.

**Comment by dlouvier** [comment] 2021-12-28 15:08
_I am going to reach out to our Autopilot contacts to see if something has changed on their end._

We reached out also our GCP Support and Google but we were not provided with a solution. Until now we just configured a service in front of the DD pods as mentioned [here](https://github.com/DataDog/helm-charts/issues/467#issuecomment-994998444)

**Comment by CharlyF** [comment] 2021-12-28 17:29
My hunch here is that the NAT rule is not added to the iptables by the container runtime. I see that in 1.21, autopilot uses containerd and I wonder if there has been a change since 1.19. Could you confirm if docker was used or if not what version of containerd is used in your 1.19 cluster?

With regards to using a service, I just want to clarify that if not configured properly the traces will be load balanced to agents that are not necessarily on the same node as the emitting application. This will result is incorrect tags added to the traces.
The only "solution" I know of when using a service is to use the `only local topology key` 
https://v1-20.docs.kubernetes.io/docs/concepts/services-networking/service-topology/#only-node-local-endpoints
which was rebranded as `internalTrafficPolicy` as of 1.21 but is deactivated by default in a feature gate, see the [doc here](https://kubernetes.io/docs/concepts/services-networking/service-traffic-policy/).
As (most?) feature gates can't be configured in Autopilot however, until 1.22 can be used (where this is enabled by default, I think), we would need the Autopilot team to surface this toggle.

**Comment by dlouvier** [comment] 2022-01-01 16:13
Hi @CharlyF thanks for digging and clarifying regarding the using the service. I got a support ticket opened with Datadog Support and you Solutions Engineer answered me that it is alright to use it. I'll keep an eye in our traces.

Unfortunately, I cannot answer you if we were using docker, but I don´t think so, I believe standard autopilot comes with containerd and we didn´t change too from the default options. We already upgraded all of our clusters to actually get internalTrafficPolicy: local, but we got stuck 1.21 (also another support ticket we got open with autopilot, case we got the master upgraded but no the nodes), but that's another story :)

Sorry I cannot help further.

**Comment by ags** [comment] 2022-01-11 03:54
> @ags could you share the version of Kubernetes the cluster is running?

Sorry for the delay getting back to you on this @CharlyF - the version is 1.21.5-gke.1302.

**Comment by gpsouza93** [comment] 2022-01-21 20:42
Is there an update on this issue? 

I am having exactly the same problem with a GKE Autopilot cluster (version 1.21.5-gke.1302). 

Is it still necessary to create a Cluster IP service in front of Datadog agent's pods on each cluster node?

**Comment by vampolo** [comment] 2022-02-24 01:16
I'm experiencing the same problem in 1.21.6-gke.1500. `dd-trace` is not able to reach `hostIP:8126`

**Comment by cmer81** [comment] 2022-03-14 16:37
Hello,

I have exactly the same problem since the last update on my GKE cluster `1.21.6-gke.1503`.

**Comment by sasamuku** [comment] 2022-03-18 00:55
As described here, there is no reachability to hostIP because of GKE Autopilot limitations.

>HostPort and hostNetwork are not permitted
https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-overview#host_options_restrictions

If you install Helm Chart like [here](https://github.com/DataDog/helm-charts/issues/467#issue-1077938598), the following solution could help you. These are shared by Datadog Support.

- Changing `DD_AGENT_HOST` from `status.hostIP` to `datadog-agent.<namespace>.svc.cluster.local`
- Setting helm value `agents.localService.forceLocalServiceEnabled: true`

`forceLocalServiceEnabled` is written [here](https://github.com/DataDog/helm-charts/blob/9867710765119c7db862a00598e4673d953e699d/charts/datadog/values.yaml#L1254-L1261). This will prevent the data from sending the other node where the Pod is not working. As result, prevents incorrect tags added to the traces as mentioned [here](https://github.com/DataDog/helm-charts/issues/467#issuecomment-1002209454).

Please note that this is available in v1.22+. You may need update your cluster.
https://kubernetes.io/docs/concepts/services-networking/service/#internal-traffic-policy

**Comment by CharlyF** [comment] 2022-04-11 14:57
Hi all,

I heard back from Google - The following change within the CNI plugin is the root-cause of the issue :
`portmap: Apply the DNAT hairpin to the whole subnet` - https://github.com/containernetworking/plugins/pull/469

The fix is going to be available on the below versions:
1.23.5-gke.300+
1.22.8-gke.300+
1.21.10-gke.2100+
1.20.15-gke.4200+
The ETA for the rollout to complete is ~2 weeks from now.

I will close this for now, we can follow up in the upstream repo if necessary.
Thank you very much for your patience.

**Closed by CharlyF** 2022-04-11 14:57 UTC
Labels: bug, chart/datadog, agent-issue

**Comment by felipe-linares** [comment] 2022-05-19 18:00
Our GKE autopilot cluster was upgraded to 1.21.11-gke.900 but still has the same issue... any way to fix?

We have another cluster with the exact same version that doesn't have the issue....

**Comment by CharlyF** [comment] 2022-06-03 18:47
Hi @felipe-linares, sorry to hear.
1.21.11-gke.900 should not be affected but we can take a look. Do you have a ticket opened where we could follow up?
