### ISSUE TITLE
Istio autodiscovery check broken in chart 2.16.X w/ Istio 1.10.X

### ISSUE THREAD

**Issue by psaia** [DataDog/helm-charts#281] opened 2021-06-14 13:51 UTC
**Describe what happened:**

When running the latest chart (2.16.5), the Istio autodiscovery check is failing. When tailing the agent logs, the following error is seen when the istio check runs:

```
2021-06-14 13:13:31 UTC | CORE | ERROR | (pkg/collector/runner/runner.go:301 in work) | Error running check istio: [{"message": "Detected 1 error while loading configuration model `InstanceConfig`:\nmetrics -> 1\n  str type expected", "traceback": "Traceback (most recent call last):\n  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py\", line 971, in run\n    initialization()\n  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py\", line 396, in load_configuration_models\n    instance_config = self.load_configuration_model(package_path, 'InstanceConfig', raw_instance_config)\n  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py\", line 436, in load_configuration_model\n    raise_from(ConfigurationError('\\n'.join(message_lines)), None)\n  File \"<string>\", line 3, in raise_from\ndatadog_checks.base.errors.ConfigurationError: Detected 1 error while loading configuration model `InstanceConfig`:\nmetrics -> 1\n  str type expected\n"}]
```

Reverting back to version 2.12.3 resolves the problem.

**Describe what you expected:**

Istio check should successfully scrape metrics.

**Steps to reproduce the issue:**

1. Install istio 1.10.0
2. Install DD 2.16.5
3. Tail agent logs

**Additional environment details (Operating System, Cloud provider, etc):**

* GCP/GKE

**Comment by ahmed-mez** [comment] 2021-06-14 13:57
Hey @psaia 
Thank you for opening this issue, it seems to be the same problem reported in https://github.com/DataDog/datadog-agent/issues/8373

It's a regression in Agent 7.28.0 and will be fixed in 7.29.0, you can still keep the helm chart 2.16.5 and pin the agent version 7.27.0 as a workaround. Sorry for the trouble!

Closing the issue as it wasn't introduced by the helm chart but let us know if you have further questions!

Thanks.

**Closed by ahmed-mez** 2021-06-14 13:57 UTC

**Comment by psaia** [comment] 2021-06-14 14:33
Hi @ahmed-mez, I appreciate the quick response. I'm still having the issue it seems. I've attempted to pin the agent by doing the following:

```yaml
datadog:
  clusterChecksRunner:
    image:
      tag: 7.27.0
  agents:
    image:
      tag: 7.27.0
```

Is there something I'm missing?

**Comment by psaia** [comment] 2021-06-14 14:38
Thank you, @ahmed-mez. It worked.

**Comment by ahmed-mez** [comment] 2021-06-14 14:39
Glad it worked! I guess it should be something like this:

```
clusterChecksRunner:
  image:
    tag: 7.27.0
agents:
  image:
    tag: 7.27.0
```
