### ISSUE TITLE
Datadog Helm Chart - ContainerCreateError from 3.5.0 (/usr/src: read-only file system)

### ISSUE THREAD

**Issue by CmdrSharp** [DataDog/helm-charts#829] opened 2022-12-07 10:29 UTC
**Describe what happened:**
Starting from version 3.5.0, we can no longer deploy the `datadog` helm chart into our Anthos Kubernetes cluster. It creates the datadog-cluster-agent fine, but the individual datadog pods fail to spin up. More specifically, the `system-probe` container fails with `CreateContainerError`.

```
  Warning  Failed     42s                kubelet            Error: failed to generate container "fdc39d9b57c2d54333925914e847682c6a6956b763158ed8628f6a770c571397" spec: failed to generate spec: failed to mkdir "/usr/src": mkdir /usr/src: read-only file system
```

Installing 3.4.0 works fine, so this is a new regression.

**Describe what you expected:**
Pod should spin up normally.

**Steps to reproduce the issue:**

`helm install datadog -f datadog.yaml datadog/datadog --namespace datadog --version 3.5.0`

```yaml
---
targetSystem: "linux"
datadog:
  clusterName: <CLUSTER-NAME-REDACTED>
  apiKeyExistingSecret: datadog-secret
  appKeyExistingSecret: datadog-secret
  site: datadoghq.eu
  kubeStateMetricsEnabled: false
  kubeStateMetricsCore:
    enabled: true
    collectVpaMetrics: true
  logs:
    enabled: true
    containerCollectAll: true
  apm:
    portEnabled: true
  helmCheck:
    enabled: true
    collectEvents: true
  networkMonitoring:
    enabled: true
  serviceMonitoring:
    enabled: true
  prometheusScrape:
    enabled: false
  processAgent:
    enabled: true
    processCollection: true
  containerExclude: "image:gcr.io/gke-on-prem-release/fluent-bit"
clusterAgent:
  replicas: 2
  createPodDisruptionBudget: true
  admissionController:
    mutateUnlabelled: true
agents:
  useConfigMap: true
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
  customAgentConfig:
    kubelet_tls_verify: false
    vector:
      logs:
        enabled: true
        url: "http://vector-haproxy.datadog:8282/"
      metrics:
        enabled: true
        url: "http://vector-haproxy.datadog:8282/"
```

**Additional environment details (Operating System, Cloud provider, etc):**
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-21T20:21:49Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.7-gke.1400", GitCommit:"cec695fcf394f7b5cc56b7bc70b5ecf99d043455", GitTreeState:"clean", BuildDate:"2022-11-02T09:29:16Z", GoVersion:"go1.18.7b7", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by CharlyF** [comment] 2022-12-07 19:28
Hi @CmdrSharp - Apologies about this. We are taking a look now.

**Comment by soudaburger** [comment] 2022-12-08 15:07
Any updates here? This basically breaks deployments for us currently.

https://github.com/DataDog/helm-charts/blob/5fb027e45d5e4c774e66f5969972f097772cd2a6/charts/datadog/templates/_helpers.tpl#L622

It appears that because we have `.Values.datadog.serviceMonitoring.enabled` set to `true`, this is being enabled for us.  Is there a reason that `.Values.datadog.serviceMonitoring.enabled` should be included in `runtime-compilation-enabled` ?

**Comment by CmdrSharp** [comment] 2022-12-08 15:39
@soudaburger One workaround, if this is breaking stuff for you currently, would be to pin the 3.4.0 release. One might say that it's usually wise to pin helm-charts to a release anyway (at least for production).

**Comment by soudaburger** [comment] 2022-12-08 15:57
We do, I would just prefer to obviously have this issue resolved with another minor release than rollback... we just can't upgrade any clusters with newer versions until this is resolved.

**Comment by ISauve** [comment] 2022-12-08 19:37
@soudaburger  In new agent versions runtime compilation is enabled by default when service monitoring is turned on, which is why `runtime-compilation-enabled` now returns `true` when `.Values.datadog.serviceMonitoring.enabled ` is set.

We have isolated the root cause of this error and are working on a fix, but in the meantime setting `systemProbe.enableDefaultKernelHeadersPaths` to `false` should solve this issue for you.

**Comment by soudaburger** [comment] 2022-12-09 12:54
I have validated setting `datadog.systemProbe.enableDefaultKernelHeadersPaths` allows the agent to deploy properly.  Thanks!

**Closed** 2023-01-19 18:46 UTC
Labels: bug

**Comment by CharlyF** [comment] 2023-01-19 20:42
Hello everyone - I just wanted to circle back on this. we have introduced the `providers.gke.cos` option to be more user friendly. 
We are going to update our doc to reflect this change to.

**Comment by johanneswuerbach** [comment] 2023-01-20 07:34
Looks like the publishing of datadog chart version 3.8.0 didn't work https://github.com/DataDog/helm-charts/actions/runs/3961473476/jobs/6786946398 and it isn't available on the chart index 🤔
