### ISSUE TITLE
Infrastructure metrics and logs tags do not match

### ISSUE THREAD

**Issue by caleb15** [DataDog/helm-charts#327] opened 2021-07-26 21:43 UTC
**Describe what happened:**
I graphed kubernetes_state.job.failed summed by job_name. When I click on a failed job in the graph and click on view related logs it opens up a log search with `job_name:companystatsweekly`, like so:

https://app.datadoghq.com/logs?live=false&from_ts=1627289580000&to_ts=1627289640000&query=job_name%3Acompanystatsweekly&index=

However, this tag does not exist in the logs. The logs instead have a tag called `kube_cronjob`. This tag is not present in metrics.

**Describe what you expected:**
I would expect that tags to match so that the integration between metrics and logs works.

**Steps to reproduce the issue:**
1. Deploy a kubernetes cluster with a failing cronjob
2. Deploy the datadog helm chart with helmfile like so:

```yml
repositories:
- name: datadog
  url: https://helm.datadoghq.com
# https://github.com/DataDog/helm-charts/blob/master/charts/datadog

releases:
  - name: datadog
    namespace: logging
    chart: datadog/datadog
    version: 2.16.5
    atomic: true
    installed: true
    values:
    - "./values/base/base.yaml.gotmpl"
    - datadog:
        site: datadoghq.com
        apiKey: {{ env "DATADOG_API_KEY" }}
        kubeStateMetricsEnabled: false # already deployed by prometheus
        env:
          - name: DD_ENV
            value: {{ .Environment.Name }}
        apm:
          enabled: true
        logs:
          enabled: true
          containerCollectAll: true
```
3. Graph kubernetes_state.job.failed summed by job name
4. Click on the failing job in the graph
5. Click on view related logs
Expected result: Logs shown
Actual result: No logs

**Additional environment details (Operating System, Cloud provider, etc):**
Kubernetes version 1.20.

**Comment by caleb15** [comment] 2021-07-26 21:44
Here's a perhaps relevant snippet from our cronjob helm chart:

```yml
{{- range $instance, $details := .Values.jobs }}{{ if $details.enabled }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ $instance }}"
  labels:
    name: cron
    instance: "{{ $instance }}"
  annotations:
    chart/version: "{{ $.Chart.Version }}"
spec:
  schedule: "{{ $details.schedule }}"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        name: cron
        instance: "{{ $instance }}"
        tags.datadoghq.com/env: {{ $.Values.vpc_name }}
        tags.datadoghq.com/service: {{ $.Release.Name }}
        tags.datadoghq.com/version: {{ $.Values.image.tag | trunc 7 | quote }}
    spec:
      # If the job as a whole fails, let it fail. We want to be aware of
      # failing jobs.
      backoffLimit: 0
      template:
        metadata:
          labels:
            name: cron
            instance: {{ $instance }}
            tags.datadoghq.com/env: {{ $.Values.vpc_name }}
            tags.datadoghq.com/service: {{ $.Release.Name }}
            tags.datadoghq.com/version: {{ $.Values.image.tag | trunc 7 | quote }}
          annotations:
            ad.datadoghq.com/{{ $instance }}.logs: '[{"source": "python"}]'
        spec:
```

**Comment by caleb15** [comment] 2021-07-26 21:48
Also we're using kube-state-metrics image v1.9.8

**Comment by ahmed-mez** [comment] 2021-07-27 13:57
hey @caleb15 thanks for reporting this! a fix is merged and will be available in datadog agent 7.31

**Closed** 2021-07-27 13:56 UTC
Labels: agent-issue, bug, chart-datadog

**Comment by caleb15** [comment] 2021-07-27 15:47
Wow, what a fast fix! :D Thank you! I'm going to wait for the new helm chart version and then I'll test it and let you know if it's working.

**Comment by ahmed-mez** [comment] 2021-07-27 15:50
@caleb15 the fix is in the datadog-agent code not in the helm chart, it will take few weeks before it's released

**Comment by caleb15** [comment] 2021-07-27 17:12
Yep, that's fine. One thing I've noticed is that the PR appears to map `job_name` to `kube_job`. I'm probably just not understanding the PR correctly but I think those two are seperate things? `job_name` is the name without a unique identifier, like `foo`. `kube_job` is the name *with* the unique identifier, like `foo-141521524`.

For example here's some tags on one of our logs:
![image](https://user-images.githubusercontent.com/46505081/127187030-92c74ddd-a044-43c8-b383-c3af178d2da1.png)

And here's the tag in my graph:
![image](https://user-images.githubusercontent.com/46505081/127187427-5d2a90d3-f659-4433-a2f8-afa3d391867d.png)
You can see that the value matches with the `kube_cronjob` tag but not the `kube_job`.

**Comment by ahmed-mez** [comment] 2021-07-28 07:15
Yes we [trim the timestamp from the job name](https://github.com/DataDog/integrations-core/blob/master/kubernetes_state/datadog_checks/kubernetes_state/kubernetes_state.py#L562) on purpose, we do it to control the metrics cardinality.

As documented [here](https://docs.datadoghq.com/getting_started/tagging/#defining-tags):
> Tags shouldn’t originate from unbounded sources, such as epoch timestamps, user IDs, or request IDs.

**Comment by caleb15** [comment] 2021-07-28 20:35
So after this will the value of `kube_job` in the screenshot above be just `healthcheck`? 🤔 I'm sure the PR fixes the issue but I'm not quite understanding how it does so, sorry. I'm curious but if you're busy I understand.

**Comment by ahmed-mez** [comment] 2021-07-29 07:20
@caleb15 no worries, yes if your k8s job is part of a cronjob then yes the timestamp suffix will be trimmed (for the reasons I explained in my previous comment).

The PR maps the `job_name` label exposed by KSM to a Datadog tag `kube_job`, to make `kubernetes_state.*` metrics use the same tag name as `kubernetes.*` metrics, logs and APM. It will make the correlation easier for you.

Related to this topic, I highly recommend reading about [Unified Service Tagging](https://docs.datadoghq.com/getting_started/tagging/unified_service_tagging/?tab=kubernetes).

I hope this clarifies things but feel free to [reach out to our support team](https://www.datadoghq.com/support/) if needed :)

Thanks!

**Comment by caleb15** [comment] 2021-10-01 20:26
This is still an issue with datadog helm chart version 2.22.1, agent 7.31. I don't think I explained the problem properly, so I'll try to restate it more clearly:

I have a metrics graph with this query: `sum:kubernetes_state.job.failed{$env} by {job_name}.as_count()`. When I click on view related logs I expected to see the related logs for that job.

![image](https://user-images.githubusercontent.com/46505081/135663177-7d1a6e3f-7ae7-497b-8c51-fa02ca65b683.png)

However, it does not show me any logs. To be specific, it takes me to the logs page with the search `job_name:recurly-sync-invoices env:cloud51`. The logs are not indexed with that tag key/value pair, so they do not appear in that search. The logs have the following tags, among others:

```
kube_container_name:recurly-sync-invoices
kube_cronjob:recurly-sync-invoices
kube_job:recurly-sync-invoices-27217629
```

These are the default tags datadog adds to logs. In the metrics graph the tags available to group by are `job_name` or `kube_job`. `job_name` does not match with any tag key above. `kube_job` does, *but* in the metrics graph it just has the value recurly-sync-invoices. This does not match the value of the kube_job key in the logs, which is recurly-sync-invoices-27217629.

You can see the datadog labels I use for the cronjob in question in the [comment above](https://github.com/DataDog/helm-charts/issues/327#issuecomment-887048528).

**Comment by caleb15** [comment] 2021-10-17 23:13
@ahmed-mez following up on this

**Comment by ahmed-mez** [comment] 2021-10-18 08:09
@caleb15 Sorry for the trouble, could you please open a [support ticket](https://www.datadoghq.com/support/)? It will be easier to track the issue plus the support team will redirect to the right team, as this might be not related to the helm chart itself.

Thanks!

**Comment by caleb15** [comment] 2021-12-09 20:43
@ahmed-mez  I reached out to support and they confirmed this is a issue with the tag names in kubernetes_state. I was able to fix it by migrating to kubernetes_state_core, like so:

```yml
  kubeStateMetricsCore:
    enabled: true
  kubeStateMetricsEnabled: false
```
It looks like you were the one who added this feature, thanks :)

Given that kubernetes_state does not work well I would recommend enabling kubeStateMetricsCore by default.

**Comment by ahmed-mez** [comment] 2021-12-10 08:22
Hi @caleb15
Glad to hear that the issue is solved and that you're satisfied with the ksm core check. It is definitely going to be enabled by default in the next major helm chart release. Really appreciate the feedback! Thanks :)
