### ISSUE TITLE
Missing tags on logs shipped by the Datadog Agent Helm package

### ISSUE THREAD

**Issue by michelzanini** [DataDog/helm-charts#455] opened 2021-12-03 13:17 UTC
**Describe what happened:**

I am adding fixed tags on the agent configuration as follows:

Helm `values.yaml`:
```
datadog:
    tags:
        - "environment:sandbox"
```

In turn this configuration deploys a agent where it contains:

```
env:
(...)
        - name: DD_TAGS
          value: 'environment:sandbox'
(...)
```

**Describe what you expected:**

I would expect that **ALL** logs and metrics shipped by the agent with this configuration would contain a `environment` tag.

**BUT**,

What happens is that if a node is just created (an auto-scaling event will create a new node), for a short period of time, logs and metrics get shipped **without** the `environment` tag.

**Steps to reproduce the issue:**

Cause the EKS/K8S cluster to add a new node. The daemon set will be deployed to it, but for a short period of time you get logs/metrics without the `environment` tag.

**Additional environment details (Operating System, Cloud provider, etc):**

Agent: Installed via Helm
Cloud provider: AWS EKS

**Comment by ahmed-mez** [comment] 2021-12-17 12:23
Hi @michelzanini 

Thank you for opening the issue and sorry for the trouble!

The behavior you described can happen in certain circumstances but it's not caused by or related to the helm chart. Could you please [contact our support team](https://www.datadoghq.com/support/) ? They will redirect to the right team and help you solve the problem. Thanks!

I'm closing the issue but let us know if you have further questions!

**Closed by ahmed-mez** 2021-12-17 12:23 UTC
Labels: chart/datadog, agent-issue
