### ISSUE TITLE
Helm install fails: Error calling semverCompare: Invalid Semantic Version

### ISSUE THREAD

**Issue by nodesocket** [DataDog/helm-charts#712] opened 2022-08-10 21:21 UTC
## Describe what happened:

> Error: INSTALLATION FAILED: template: datadog/templates/daemonset.yaml:114:14: executing "datadog/templates/daemonset.yaml" at <include "container-process-agent" .>: error calling include: template: datadog/templates/_helpers.tpl:689:32: executing "process-agent-config-file-flag" at <semverCompare "^6.36.0 || ^7.36.0" $version>: error calling semverCompare: Invalid Semantic Version

**This is blocking us from installing the DataDog agent in Kubernetes clusters. This previously worked, thus I believe is a regression.**

## Describe what you expected:

Helm install should complete.

## Steps to reproduce the issue:

```shell
helm install datadog -f values/datadog.yaml --set datadog.apiKey=<DATADOG_API_KEY_HERE> --set datadog.clusterName=<ENV_NAME_HERE> datadog/datadog
```

Contents of `values/datadog.yaml` is:

```
datadog:
  confd:
    traefik.yaml: |-
      ad_identifiers:
        - traefik
      init_config:
      instances:
        - host: traefik-dashboard
          port: 80
  env:
    - name: "DD_KUBELET_TLS_VERIFY"
      value: "false"
    - name: "RABBITMQ_PASSWORD"
      value: "<RABBITMQ_PASSWORD_HERE>"
  systemProbe:
    enableOOMKill: true
```

## Additional environment details (Operating System, Cloud provider, etc):

Helm version: `version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.17.5"}`

**Comment by CharlyF** [comment] 2022-08-11 14:08
Hi @nodesocket - Sorry about this, I am adding this to our backlog.

**Comment by nodesocket** [comment] 2022-08-11 18:17
@CharlyF is this a known issue then? Want to confirm it's nothing I am doing on my end.

**Comment by betabrandao** [comment] 2022-11-08 21:41
@nodesocket try with helm v3.10.1

**Comment by fanny-jiang** [comment] 2023-10-11 21:22
Hi @nodesocket, I apologize for the delay and thank you for reaching out. I'm unable to reproduce the error at this time. 

I'm using helm `version.BuildInfo{Version:"v3.12.1", GitCommit:"f32a527a060157990e2aa86bf45010dfb3cc8b8d", GitTreeState:"clean", GoVersion:"go1.20.5"}` and tested with the provided `values.yaml` using the most recent agent image tag version, `7.35.0`, and `7.36.0` in an attempt to trigger the error. 

I'll close this issue for now since some time has passed and we haven't received more recent reports of the problem. Please do open a new issue if this occurs again.

**Closed by fanny-jiang** 2023-10-11 21:22 UTC
Labels: bug
